### ISSUE TITLE
Udělat výpis projektu deklarativní (json/yaml)

### ISSUE THREAD

**Issue by burningtree** [gweicz/web#2]
Volitelný úkol - předpokládám, že výpis projektů bude nejvíce aktualizovaný, proto by se hodilo mít to deklarované někde separátně bez HTML omáčky.

Navrhovaný zápis (yaml):
```yaml
projects:

  - name: Ethereum/DeFi Příručka
    desc: Příručka pro nováčky, sloužící jako průvodce ekosystémem Etherea.
    url: https://prirucka.gwei.cz/
    ico: prirucka

  - name: Novinkový web
    desc: Novinky se světa kryptoměn, s hlavním zaměřením na Ethereum/DeFi.
    url: https://forum.gwei.cz/t/novinkovy-web-o-kryptomenach/232
    label: Ve vývoji
    ico: news

...
```
